compatibility_date = "2024-08-21"
main = "index.ts"
name = "northwind-worker"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-09-23"

[observability]
enabled = true

[dev]
port=8789

[placement]
mode = "smart"

[[d1_databases]]
binding = "DB"
database_name = "northwind"
database_id = "d2757109-c1bf-4a66-b325-4d9c09b3e3a7"