compatibility_date = "2024-08-21"
main = "index.ts"
name = "northwind-worker"
observability.logs.enabled = true

[placement]
mode = "smart"

[[d1_databases]]
binding = "DB"
database_name = "northwind"
database_id = "d2757109-c1bf-4a66-b325-4d9c09b3e3a7"